# Copyright (C) 2019 cspiel.at
# Copyright (C) 2021 Dalei Liu

RSUA_CURDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
RSUA_TOPDIR := $(RSUA_CURDIR)/../..

MOD		:= i2s
$(MOD)_SRCS	+= i2s.c

include $(RSUA_TOPDIR)/mk/mod.mk
