# Copyright (C) 2010 - 2015 Creytiv.com
# Copyright (C) 2020 Dalei Liu

RSUA_CURDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
RSUA_TOPDIR := $(RSUA_CURDIR)/../..

MOD		:= account
$(MOD)_SRCS	+= account.c

include $(RSUA_TOPDIR)/mk/mod.mk
