# Copyright (C) 2020 Commend.com - c.spielberger@commend.com
# Copyright (C) 2020 Dalei Liu

RSUA_CURDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
RSUA_TOPDIR := $(RSUA_CURDIR)/../..

MOD		:= serreg
$(MOD)_SRCS	+= serreg.c

include $(RSUA_TOPDIR)/mk/mod.mk
